2021-11-26 01:51:12,230 INFO    MainThread:45388 [wandb_setup.py:_flush():71] setting env: {}
2021-11-26 01:51:12,230 INFO    MainThread:45388 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-26 01:51:12,230 INFO    MainThread:45388 [wandb_init.py:_log_setup():371] Logging user logs to /opt/ml/code/wandb/run-20211126_015112-2xa2auh9/logs/debug.log
2021-11-26 01:51:12,230 INFO    MainThread:45388 [wandb_init.py:_log_setup():372] Logging internal logs to /opt/ml/code/wandb/run-20211126_015112-2xa2auh9/logs/debug-internal.log
2021-11-26 01:51:12,230 INFO    MainThread:45388 [wandb_init.py:init():404] calling init triggers
2021-11-26 01:51:12,230 INFO    MainThread:45388 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2021-11-26 01:51:12,231 INFO    MainThread:45388 [wandb_init.py:init():449] starting backend
2021-11-26 01:51:12,231 INFO    MainThread:45388 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-11-26 01:51:12,241 INFO    MainThread:45388 [backend.py:ensure_launched():199] starting backend process...
2021-11-26 01:51:12,248 INFO    MainThread:45388 [backend.py:ensure_launched():205] started backend process with pid: 45431
2021-11-26 01:51:12,250 INFO    MainThread:45388 [wandb_init.py:init():458] backend started and connected
2021-11-26 01:51:12,251 INFO    MainThread:45388 [wandb_init.py:init():519] updated telemetry
2021-11-26 01:51:12,254 INFO    MainThread:45388 [wandb_init.py:init():549] communicating current version
2021-11-26 01:51:13,072 INFO    MainThread:45388 [wandb_init.py:init():554] got version response 
2021-11-26 01:51:13,072 INFO    MainThread:45388 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-11-26 01:51:13,293 INFO    MainThread:45388 [wandb_init.py:init():592] starting run threads in backend
2021-11-26 01:51:18,275 INFO    MainThread:45388 [wandb_run.py:_console_start():1816] atexit reg
2021-11-26 01:51:18,276 INFO    MainThread:45388 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.REDIRECT
2021-11-26 01:51:18,277 INFO    MainThread:45388 [wandb_run.py:_redirect():1695] Redirecting console.
2021-11-26 01:51:18,280 INFO    MainThread:45388 [wandb_run.py:_redirect():1751] Redirects installed.
2021-11-26 01:51:18,280 INFO    MainThread:45388 [wandb_init.py:init():619] run started, returning control to user process
2021-11-26 01:58:07,025 INFO    MainThread:45388 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 1
2021-11-26 01:58:07,025 INFO    MainThread:45388 [wandb_run.py:_restore():1758] restore
2021-11-26 01:58:09,798 INFO    MainThread:45388 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 507
  total_bytes: 507
}

2021-11-26 01:58:10,033 INFO    MainThread:45388 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 507
  total_bytes: 507
}

2021-11-26 01:58:10,487 INFO    MainThread:45388 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 507
  total_bytes: 48282
}

2021-11-26 01:58:10,590 INFO    MainThread:45388 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 507
  total_bytes: 48282
}

2021-11-26 01:58:10,693 INFO    MainThread:45388 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 507
  total_bytes: 48282
}

2021-11-26 01:58:10,795 INFO    MainThread:45388 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 48282
  total_bytes: 48282
}

2021-11-26 01:58:10,897 INFO    MainThread:45388 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 48282
  total_bytes: 48282
}

2021-11-26 01:58:10,999 INFO    MainThread:45388 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 48282
  total_bytes: 48282
}

2021-11-26 01:58:11,101 INFO    MainThread:45388 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 48282
  total_bytes: 48282
}

2021-11-26 01:58:11,203 INFO    MainThread:45388 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 48282
  total_bytes: 48282
}

2021-11-26 01:58:11,726 INFO    MainThread:45388 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 48282
  total_bytes: 48282
}

2021-11-26 01:58:12,196 INFO    MainThread:45388 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 48282
  total_bytes: 48282
}
local_info {
}

2021-11-26 01:58:13,377 INFO    MainThread:45388 [wandb_run.py:_append_files():2184] logging synced files
